### ISSUE TITLE
Software Name and Logo

### ISSUE THREAD

**Issue by st-te** [PriyaGordon/python-intermediate-rivercatchment#10]
Need name/logo for our software

**Comment by st-te** [comment]
Made a beautiful logo and we are calling it **CatchmentAnalyser**_Pro_

**Comment by qq23840** [comment]
I need to see evidence of this beautiful logo

**Comment by st-te** [comment]
![Image](https://github.com/PriyaGordon/python-intermediate-rivercatchment/assets/93257279/da9f0a33-b903-427d-ba2d-b614db545440)
