### ISSUE TITLE
Badge on README.md

### ISSUE THREAD

**Issue by HannahCJL** [PriyaGordon/python-intermediate-rivercatchment#14]
You could add a badge to the README.md file for more fun

**Comment by st-te** [comment]
Hi HannahCJL, thanks for this constructive feedback. We actually have used ChatGPT to generate a logo for our software and plan to update the README.md file in due course. As I'm sure you can imagine, running an award-winning software startup on a limited budget can be quite a challenge! 

![396adf79-2f6b-43ea-946a-f93208f1a76a](https://github.com/PriyaGordon/python-intermediate-rivercatchment/assets/93257279/26413705-01f1-4c9d-b56a-fe946bc080bb)

**Comment by HannahCJL** [comment]
Thanks for your response. My working hours are 9-5 Monday to Thursday
