### ISSUE TITLE
Remove example.ipynb from the repository.

### ISSUE THREAD

**Issue by pearson01** [PriyaGordon/python-intermediate-rivercatchment#15]
This file has absolutely no place being in this repo. It reflects very poorly on the development team, and indicates it has been produced by amateurs.

**Comment by pearson01** [comment]
Upon further review, the example.ipynb can already be found in the .gitignore file. This underlines the disorganised nature of the development team. Careless.

**Comment by st-te** [comment]
[😭](https://emojipedia.org/loudly-crying-face)
