### ISSUE TITLE
catchment/compute_data reorder

### ISSUE THREAD

**Issue by meredithburke** [PriyaGordon/python-intermediate-rivercatchment#18]
UHM Might be more helpful to have the def compute_standard_deviation before def analyse_data since it's using that former function.

**Comment by qq23840** [comment]
I think you'll find the ordering of functions is irrelevant in this case. Please refrain from frivolous criticism in the future. 

We have a zero tolerance policy against discrimination, harassment or bullying at RiverAnalyserPro and refer you to our code of conduct found at https://www.youtube.com/watch?v=tDOM-U7uStM

**Comment by HannahCJL** [comment]
dogs!!
