### ISSUE TITLE
we can't read your XML files

### ISSUE THREAD

**Issue by meredithburke** [PriyaGordon/python-intermediate-rivercatchment#20]
Throwing stones and such

**Comment by st-te** [comment]
Hi Meredithburke, thanks for your super constructive feedback! 

Just so you're aware in our upcoming version 1.1.0 we plan to add support for every type of file in existence. 

Just reach out if you have any further questions, here at **RiverAnalyser**_Pro_ we'd be more than happy to help!! 😊

**Comment by st-te** [comment]
OK RiverAnalyserPro team, I've added an xml class - time for @qq23840 to test this badboi!

**Comment by st-te** [comment]
XML tests PASSED. Great job team.
